### PR TITLE
Update TYPO3 to v12.3.0

### PR DESCRIPTION
**Pull request by d-pietka**
Update TYPO3 to v12.3.0

### CODE REVIEW

**Comment by tmotyl** [comment]
@d-pietka why new branch instead of using v12?

**Comment by d-pietka** [comment]
> @d-pietka why new branch instead of using v12?

@lukaszuznanski asked me to create a new branch

**Comment by tmotyl** [comment]
But is this based on top of v12 branch? The thing is that we have already communicated the v12 branch in few places.
Anyway, we should tag current version and release a new v12 compat version.

**Comment by d-pietka** [comment]
> But is this based on top of v12 branch? The thing is that we have already communicated the v12 branch in few places. Anyway, we should tag current version and release a new v12 compat version.

yes, branch 12.03. is from branch v12, I will discuss it with @lukaszuznanski and change it if necessary

**Comment by d-pietka** [comment]
This MR can be removed, I added a new MR from branch v12 to master 

https://github.com/TYPO3-Headless/pwa-demo/pull/81

**Pull request closed without merging**
